# Netlify configuration for PrintFarm Manager
# TanStack Start application deployment

[build]
  # Build command - same as local development
  command = "npm run build"

  # Publish directory - TanStack Start outputs to .output
  publish = ".output/public"

  # Functions directory - TanStack Start generates server functions
  functions = ".output/server"

[build.environment]
  # Node.js version
  NODE_VERSION = "22"

# Redirect all requests to server functions (SSR)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
