# Solution Architecture Workflow Configuration
name: solution-architecture
description: "Scale-adaptive solution architecture generation with dynamic template sections. Replaces legacy HLA workflow with modern BMAD Core compliance."
author: "BMad Builder"

# Critical variables
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
date: system-generated

# Input requirements
inputs:
  - name: prd_path
    description: "Path to PRD document"
    default: "{output_folder}/PRD.md"
    required: true
  - name: project_workflow_analysis_path
    description: "Path to project-workflow-analysis.md from plan-project workflow"
    default: "{output_folder}/project-workflow-analysis.md"
    required: true
  - name: project_level
    description: "Project level (0-4) from analysis file"
    type: integer
    required: true

# Output artifacts
outputs:
  - name: architecture_md
    description: "Complete solution architecture document"
    default: "{output_folder}/solution-architecture.md"
  - name: architecture_decisions_md
    description: "Architecture Decision Records (ADRs)"
    default: "{output_folder}/architecture-decisions.md"
  - name: epic_alignment_matrix
    description: "Epic-to-component mapping (from cohesion check)"
  - name: tech_specs
    description: "Per-epic tech spec documents"

# Workflow variables (set during execution)
variables:
  user_skill_level: "intermediate"
  project_type: ""
  architecture_style: ""
  repo_strategy: ""
  template_sections: []

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/3-solutioning"
adr_template: "{installed_path}/ADR-template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Reference data files
architecture_registry: "{installed_path}/templates/registry.csv"
project_types_questions: "{installed_path}/project-types"

# Default output location
default_output_file: "{output_folder}/solution-architecture.md"

# Additional workflow dependencies
tech_spec_workflow: "{project-root}/bmad/bmm/workflows/3-solutioning/tech-spec/workflow.yaml"

web_bundle:
  name: "solution-architecture"
  description: "Scale-adaptive solution architecture generation with dynamic template sections. Replaces legacy HLA workflow with modern BMAD Core compliance."
  author: "BMad Builder"
  instructions: "bmad/bmm/workflows/3-solutioning/instructions.md"
  validation: "bmad/bmm/workflows/3-solutioning/checklist.md"
  tech_spec_workflow: "bmad/bmm/workflows/3-solutioning/tech-spec/workflow.yaml"
  # Reference data files
  architecture_registry: "bmad/bmm/workflows/3-solutioning/templates/registry.csv"
  project_types_questions: "bmad/bmm/workflows/3-solutioning/project-types"
  web_bundle_files:
    - "bmad/bmm/workflows/3-solutioning/instructions.md"
    - "bmad/bmm/workflows/3-solutioning/checklist.md"
    - "bmad/bmm/workflows/3-solutioning/ADR-template.md"
    - "bmad/bmm/workflows/3-solutioning/templates/registry.csv"
    - "bmad/bmm/workflows/3-solutioning/templates/backend-service-architecture.md"
    - "bmad/bmm/workflows/3-solutioning/templates/cli-tool-architecture.md"
    - "bmad/bmm/workflows/3-solutioning/templates/data-pipeline-architecture.md"
    - "bmad/bmm/workflows/3-solutioning/templates/desktop-app-architecture.md"
    - "bmad/bmm/workflows/3-solutioning/templates/embedded-firmware-architecture.md"
    - "bmad/bmm/workflows/3-solutioning/templates/game-engine-architecture.md"
    - "bmad/bmm/workflows/3-solutioning/templates/game-engine-godot-guide.md"
    - "bmad/bmm/workflows/3-solutioning/templates/game-engine-unity-guide.md"
    - "bmad/bmm/workflows/3-solutioning/templates/game-engine-web-guide.md"
    - "bmad/bmm/workflows/3-solutioning/templates/infrastructure-architecture.md"
    - "bmad/bmm/workflows/3-solutioning/templates/library-package-architecture.md"
    - "bmad/bmm/workflows/3-solutioning/templates/mobile-app-architecture.md"
    - "bmad/bmm/workflows/3-solutioning/templates/web-api-architecture.md"
    - "bmad/bmm/workflows/3-solutioning/templates/web-fullstack-architecture.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/backend-questions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/cli-questions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/data-questions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/desktop-questions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/embedded-questions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/extension-questions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/game-questions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/infra-questions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/library-questions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/mobile-questions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/web-questions.md"
